import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopNav from "@/components/TopNav";
import { getCategories } from "@/actions/category";
import { PreviewProvider } from "@/components/PreviewContext";
import { ViewProvider } from "@/components/ViewContext";

export const dynamic = 'force-dynamic';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SaveMyLink",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let categories = [];
  try {
    categories = await getCategories();
  } catch (error) {
    console.warn("Failed to fetch categories. Database might not be connected yet.");
  }

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <PreviewProvider>
          <ViewProvider>
            <TopNav initialCategories={categories} />
            {children}
          </ViewProvider>
        </PreviewProvider>
      </body>
    </html>
  );
}
